import { Colors } from "../../theme/Colors";

export default {
  modules: ["Toolbar", "Resize"],
  overlayStyles: {
    position: "absolute",
    boxSizing: "border-box",
    boxShadow: "rgb(5, 137, 243) 0 0 0 1px",
  },
  handleStyles: {
    position: "absolute",
    height: "12px",
    width: "12px",
    backgroundColor: "white",
    border: `1px solid ${Colors.primary}`,
    boxSizing: "border-box",
    opacity: "0.80",
  },
  displayStyles: {
    position: "absolute",
    font: "12px/1.0 Arial, Helvetica, sans-serif",
    padding: "4px 8px",
    textAlign: "center",
    backgroundColor: "white",
    color: Colors.primary,
    border: "1px solid #777",
    boxSizing: "border-box",
    opacity: "0.80",
    cursor: "default",
  },
  toolbarStyles: {
    position: "absolute",
    top: "-12px",
    right: "0",
    left: "0",
    height: "0",
    minWidth: "100px",
    font: "12px/1.0 Arial, Helvetica, sans-serif",
    textAlign: "center",
    color: Colors.primary,
    boxSizing: "border-box",
    cursor: "default",
  },
  toolbarButtonStyles: {
    display: "inline-block",
    width: "24px",
    height: "24px",
    background: "white",
    border: `1px solid #000`,
    verticalAlign: "middle",
  },
  toolbarButtonSvgStyles: {
    fill: Colors.primary,
    stroke: Colors.primary,
    strokeWidth: "2",
  },
};
